window.CATALOG = [
  { code: "sap", name: "Code SAP", type: "Texte", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Oui", note: "Pas required. Masque + maskMin 6. Cle import n°2." },
  { code: "ean", name: "Code EAN/GTIN", type: "Texte", groupInit: "Informations generales", extra: "", req: "Oui", cpl: "Oui", note: "Masque 14 chiffres. Cle import n°1." },
  { code: "nom", name: "Nom produit", type: "Texte", groupInit: "Informations generales", extra: "", req: "Oui", cpl: "Oui", note: "Titre de synthese." },
  { code: "created_at", name: "Date de creation", type: "Date", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Non", note: "Systeme, readonly. Valeur = product.createdAt." },
  { code: "updated_at", name: "Date de derniere MAJ", type: "Date", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Non", note: "Systeme, readonly. Valeur = product.maj." },
  { code: "cat", name: "Categorie", type: "Simple select", groupInit: "Informations generales", extra: "Conditions commerciales", req: "Oui", cpl: "Non", note: "Systeme. Identite produit, pas fields." },
  { code: "completion", name: "Completion", type: "Nombre", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Non", note: "Systeme. Calcule JS, pas une formule." },
  { code: "active_o", name: "Actif canal O", type: "Oui / Non", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Oui", note: "Source de statut_publication." },
  { code: "active_l", name: "Actif canal L", type: "Oui / Non", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Oui", note: "Source de statut_publication." },
  { code: "statut_publication", name: "Statut de publication", type: "Texte", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Non", note: "Calcule SI(active_o OU active_l)." },
  { code: "date_maj_statut", name: "Date MAJ statut", type: "Date", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Non", note: "DATE_MAJ(statut_publication)." },
  { code: "statut_commercial", name: "Statut commercial", type: "Simple select", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Oui", note: "Actif / Inactif / Ecoulement / En cours / Arrete." },
  { code: "miseEnLigne", name: "Date de mise en ligne", type: "Date", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "code_ecommerce", name: "Code e-commerce", type: "Texte", groupInit: "Informations generales", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "visuel_face", name: "Vue de face", type: "Image", groupInit: "Visuels", extra: "", req: "Non", cpl: "Non", note: "Hors completion. Vignette de liste possible." },
  { code: "visuel_tq", name: "Vue 3/4", type: "Image", groupInit: "Visuels", extra: "", req: "Non", cpl: "Non", note: "Hors completion." },
  { code: "visuel_profil", name: "Vue de profil", type: "Image", groupInit: "Visuels", extra: "", req: "Non", cpl: "Non", note: "Hors completion." },
  { code: "visuel_ambiance", name: "Visuel ambiance", type: "Image", groupInit: "Visuels", extra: "", req: "Non", cpl: "Non", note: "Hors completion." },
  { code: "visuel_fournisseur", name: "Visuel fournisseur", type: "Image", groupInit: "Visuels", extra: "", req: "Non", cpl: "Non", note: "Hors completion." },
  { code: "fournisseur_code", name: "Code fournisseur", type: "Texte", groupInit: "Conditions commerciales", extra: "", req: "Non", cpl: "Non", note: "Systeme. Matching brandSettings." },
  { code: "marque", name: "Marque", type: "Simple select", groupInit: "Conditions commerciales", extra: "Caracteristiques lentille, Caracteristiques PEL", req: "Non", cpl: "Non", note: "Systeme. Unique liste de marques, extensible. En tete des caracteristiques lentille." },
  { code: "segmentation", name: "Segmentation", type: "Texte", groupInit: "Conditions commerciales", extra: "", req: "Non", cpl: "Non", note: "Systeme. Ligne brand, pas saisie produit." },
  { code: "rf", name: "RF", type: "Nombre", groupInit: "Conditions commerciales", extra: "", req: "Non", cpl: "Oui", note: "percent, stocke 0–1." },
  { code: "remiseEnseigne", name: "Remise interne", type: "Nombre", groupInit: "Conditions commerciales", extra: "", req: "Non", cpl: "Oui", note: "percent 0–1. Copiee depuis brand, alimente pa_interne." },
  { code: "repriseEchange", name: "Reprise echange", type: "Oui / Non", groupInit: "Conditions commerciales", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "conditionsLivraison", name: "Conditions de livraison", type: "Texte", groupInit: "Conditions commerciales", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "ref_monture", name: "Reference monture", type: "Texte", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "Entree nom_marketing + SEO." },
  { code: "nom_marketing", name: "Nom marketing", type: "Texte", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Non", note: "CONCAT(marque, ref, couleur)." },
  { code: "cible", name: "Cible", type: "Simple select", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "Homme Femme Mixte Enfant Junior." },
  { code: "optique_solaire", name: "Optique / Solaire", type: "Simple select", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "Clef de segmentation brand." },
  { code: "matiere", name: "Matiere", type: "Simple select", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "cerclage", name: "Cerclage", type: "Simple select", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "couleur", name: "Couleur", type: "Texte", groupInit: "Caracteristiques monture", extra: "Caracteristiques accessoire", req: "Non", cpl: "Oui", note: "Meme attribut sur monture et accessoire." },
  { code: "largeur_verres", name: "Largeur des verres", type: "Nombre", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "Source de taille." },
  { code: "taille", name: "Taille", type: "Texte", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Non", note: "Calcule par seuils 56 / 51 / 49 / 47 / 44 / 40." },
  { code: "forme", name: "Forme de la monture", type: "Simple select", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "code_douanier", name: "Code douanier", type: "Texte", groupInit: "Caracteristiques monture", extra: "", req: "Non", cpl: "Oui", note: "Masque 8 chiffres." },
  { code: "commentaire", name: "Commentaire", type: "Texte long", groupInit: "Caracteristiques monture", extra: "Conditions commerciales", req: "Non", cpl: "Non", note: "Hors completion. Meme objet, plusieurs groupes." },
  { code: "prix_catalogue", name: "Prix catalogue", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Oui", note: "Source PA interne." },
  { code: "pa_interne", name: "PA interne HT", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "catalogue × (1 - remise interne)." },
  { code: "remise", name: "Remise sur facture", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Oui", note: "percent, stocke 0–1, affiche %." },
  { code: "rfa", name: "RFA", type: "Nombre", groupInit: "Tarification", extra: "Conditions commerciales", req: "Non", cpl: "Oui", note: "percent 0–1. Meme attribut dans 2 groupes." },
  { code: "marge_interne", name: "Marge interne HT", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "PA opticien HT - PA interne HT. Monture seulement." },
  { code: "pa_opticien", name: "PA opticien HT", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "Prix catalogue × (1 - RF) × (1 - RFA)." },
  { code: "pvmc", name: "PVMC", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "Catalogue x 2,6 ou 1,9, euro superieur. Monture seulement." },
  { code: "prix_final", name: "Prix arrondi HT", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "PVMC / 1,2. Monture seulement." },
  { code: "taux_marque", name: "Taux de marque", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "(Prix arrondi HT - PA opticien) / prix arrondi HT. Monture seulement." },
  { code: "seo_titre_o", name: "Titre SEO O", type: "Texte", groupInit: "SEO", extra: "", req: "Non", cpl: "Non", note: "CONCAT nom | Optic 2000." },
  { code: "seo_desc_o", name: "Description SEO O", type: "Texte", groupInit: "SEO", extra: "", req: "Non", cpl: "Non", note: "Calcule." },
  { code: "seo_titre_l", name: "Titre SEO L", type: "Texte", groupInit: "SEO", extra: "", req: "Non", cpl: "Non", note: "CONCAT nom | Lissac." },
  { code: "seo_desc_l", name: "Description SEO L", type: "Texte", groupInit: "SEO", extra: "", req: "Non", cpl: "Non", note: "Calcule." },
  { code: "laboratoire", name: "Laboratoire", type: "Simple select", groupInit: "Caracteristiques lentille", extra: "Caracteristiques PEL", req: "Non", cpl: "Oui", note: "Meme attribut, 2 groupes." },
  { code: "nb_lentilles", name: "Nb lentilles par boite", type: "Simple select", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "Valeurs texte 2…180." },
  { code: "type_usage", name: "Type (lentille)", type: "Simple select", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "Correctrices / Couleurs. Homonyme type_pel." },
  { code: "type_lentille", name: "Type de lentilles", type: "Simple select", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "Souple / Rigide." },
  { code: "couleur_lentille", name: "Couleur lentille", type: "Texte", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "type_vision", name: "Type de vision", type: "Simple select", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "renouvellement", name: "Renouvellement", type: "Simple select", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "SEO lentille." },
  { code: "materiau_lentille", name: "Materiau lentille", type: "Simple select", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "hydrophilie", name: "Hydrophilie en %", type: "Nombre", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "Grandeur 0–100, pas displayFormat percent." },
  { code: "filtre_uv", name: "Filtre UV", type: "Oui / Non", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "sensibilite_o2", name: "Transmissibilite DK/t", type: "Nombre", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "hema", name: "HEMA", type: "Oui / Non", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "teinte_manip", name: "Teinte de manipulation", type: "Oui / Non", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "defauts_visuels", name: "Defauts visuels", type: "Multi select", groupInit: "Caracteristiques lentille", extra: "", req: "Non", cpl: "Oui", note: "Seul multi du catalogue." },
  { code: "prix_vente", name: "Prix de vente TTC", type: "Nombre", groupInit: "Tarification lentilles + PEL", extra: "", req: "Non", cpl: "Oui", note: "2 decimales. Lentilles et PEL." },
  { code: "prix_tva", name: "Prix de vente HT", type: "Nombre", groupInit: "Tarification lentilles + PEL", extra: "", req: "Non", cpl: "Non", note: "TTC / 1,2. 2 decimales." },
  { code: "utilisation_lentille", name: "Utilisation lentille", type: "Simple select", groupInit: "Logistique lentille", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "seo_titre_o2000_l", name: "Titre SEO O (lentille)", type: "Texte", groupInit: "SEO lentille", extra: "", req: "Non", cpl: "Non", note: "Autre code que seo_titre_o." },
  { code: "seo_desc_o2000_l", name: "Description SEO O (lentille)", type: "Texte", groupInit: "SEO lentille", extra: "", req: "Non", cpl: "Non", note: "" },
  { code: "seo_titre_lissac_l", name: "Titre SEO L (lentille)", type: "Texte", groupInit: "SEO lentille", extra: "", req: "Non", cpl: "Non", note: "" },
  { code: "seo_desc_lissac_l", name: "Description SEO L (lentille)", type: "Texte", groupInit: "SEO lentille", extra: "", req: "Non", cpl: "Non", note: "" },
  { code: "type_produit_acc", name: "Type de produit", type: "Texte", groupInit: "Caracteristiques accessoire", extra: "", req: "Non", cpl: "Oui", note: "Pas un select." },
  { code: "coefficient", name: "Coefficient", type: "Nombre", groupInit: "Caracteristiques accessoire", extra: "1 decimale", req: "Non", cpl: "Oui", note: "Grille BDD : 2 a 5, un chiffre." },
  { code: "matiere_acc", name: "Matière accessoire", type: "Texte", groupInit: "Caracteristiques accessoire", extra: "", req: "Non", cpl: "Oui", note: "Pas la liste matiere monture." },
  { code: "dimensions_acc", name: "Dimensions", type: "Texte", groupInit: "Caracteristiques accessoire", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "conditionnement_origine", name: "Conditionnement d'origine", type: "Nombre", groupInit: "Caracteristiques accessoire", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "annee_lancement", name: "Année de lancement", type: "Nombre", groupInit: "Caracteristiques accessoire", extra: "", req: "Non", cpl: "Oui", note: "Pas la date de creation." },
  { code: "designation_magasin", name: "Désignation magasin", type: "Texte", groupInit: "Caracteristiques accessoire", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "pa_unitaire", name: "PA unitaire", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Oui", note: "Accessoire seulement." },
  { code: "pa_lot", name: "PA par lot", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Oui", note: "Accessoire seulement." },
  { code: "prix_opticien_unitaire", name: "Prix opticien unitaire", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Oui", note: "Accessoire. Source du PV TTC arrondi." },
  { code: "pvmc_acc", name: "PV TTC arrondi", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "Prix opticien unitaire x coefficient, euro superieur. Accessoire seulement." },
  { code: "pv_ht_acc", name: "PV HT", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "PV TTC arrondi / 1,2. Accessoire seulement." },
  { code: "marge_acc", name: "Marge HT", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "PV HT - prix opticien unitaire. Accessoire seulement." },
  { code: "taux_acc", name: "Taux accessoire", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Non", note: "Marge / PV HT. Accessoire seulement." },
  { code: "prix_opticien_lot", name: "Prix opticien par lot", type: "Nombre", groupInit: "Tarification", extra: "", req: "Non", cpl: "Oui", note: "Accessoire seulement." },
  { code: "code_produit", name: "Code produit", type: "Texte", groupInit: "Caracteristiques PEL", extra: "", req: "Non", cpl: "Oui", note: "Distinct de sap / ean." },
  { code: "conditionnement", name: "Conditionnement", type: "Texte", groupInit: "Caracteristiques PEL", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "type_pel", name: "Type (PEL)", type: "Simple select", groupInit: "Caracteristiques PEL", extra: "", req: "Non", cpl: "Oui", note: "Homonyme type_usage." },
  { code: "type_solution", name: "Type de solution", type: "Simple select", groupInit: "Caracteristiques PEL", extra: "", req: "Non", cpl: "Oui", note: "" },
  { code: "duree_conservation", name: "Duree conservation apres ouverture", type: "Texte", groupInit: "Caracteristiques PEL", extra: "", req: "Non", cpl: "Oui", note: "" },
];
